### ISSUE TITLE
Kubernetes 1.27 support on pypi.org

### ISSUE THREAD

**Issue by trevorlauder** [willthames/kubernetes-validate#22]
It looks like 1.27 support was added in a couple weeks ago but I don't see the release on pypi.org.  Is this able to be pushed or is it still in development?

**Comment by kub3let** [comment]
@willthames any news on this ? 

kubernetes-validate is the only thing holding me back from k8s 1.27

If I try to deploy vm's using kube-virt via ansible it complains about kubernetes-validate not supporting 1.27 schema.

Happy to test any beta builds if required.

**Comment by willthames** [comment]
@trevorlauder @kub3let apologies for the delay. I've just pushed it to pypi.

**Comment by kub3let** [comment]
@willthames sorry to bother you about it, but it seems to be still missing.

https://pypi.org/project/kubernetes-validate/#history

**Comment by willthames** [comment]
@kub3let no need to be sorry, it was entirely my own fault - I'd misconfigured my pypi auth and hadn't validated that it had actually uploaded - very sorry to mess you around.

I've checked that it's there now!

**Comment by kub3let** [comment]
@willthames thank you !

**Comment by willthames** [comment]
@kub3let no problem, hopefully 1.28 will go a *lot* more smoothly!
